# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yamajid <yamajid@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/13 14:33:33 by yamajid           #+#    #+#              #
#    Updated: 2024/01/15 09:37:27 by yamajid          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Wall -Wextra -Werror -std=c++98 -o Animal Brain.cpp Animal.cpp Cat.cpp Dog.cpp main.cpp 
fclean:
	rm -rf ./Animal 
