# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yamajid <yamajid@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/15 20:54:19 by yamajid           #+#    #+#              #
#    Updated: 2024/01/17 10:21:48 by yamajid          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++  -std=c++98 -o AMateria AMateria.cpp Character.cpp Cure.cpp main.cpp Ice.cpp MateriaSource.cpp #-Wall -Wextra -Werror
fclean:
	rm -rf ./AMateria