# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yamajid <yamajid@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/13 14:33:33 by yamajid           #+#    #+#              #
#    Updated: 2024/01/13 15:50:34 by yamajid          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Wall -Wextra -Werror -std=c++98 -o Animal Animal.cpp main.cpp
clean:
	rm -rf %.o
	
# NAME = Animal

# Flags = -Wall -Wextra -Werror -std=c++98

# RM = rm -rf

# SRC = Animal.cpp main.cpp

# OBJS